RED: final frame with a strike
We have gotten into another dead-end. Our recursion pattern is failing
because the final frame can be very different when having extra rolls:

head of empty list
java.util.NoSuchElementException: head of empty list

We need our thinking hat here.